### ISSUE TITLE
Create the sign up page

### ISSUE THREAD

**Issue by ItaloCanturil** [ItaloCanturil/Vue-Habit#2]
Create sign up page with: 

[Vue Router](https://router.vuejs.org/)  - FrontEnd

[Auth API](https://github.com/ItaloCanturil/backend-habitTracker) - BackEnd

**Comment by caio-emidio** [comment]
Quais os requisitos dessa tarefa? Voce ja sabe?
Tem algum figma do front?

**Comment by caio-emidio** [comment]
Crie a task detalhada para o backend em:
https://github.com/ItaloCanturil/backend-habitTracker/issues

**Comment by ItaloCanturil** [comment]
Features:
- [x] Do validations for the form
- [x] Show error message if exists
- [x] Send data from register page to backend endpoint

UI: 
- [x] Style the inputs
- [x] Style the validations errors with red color
- [x] Style button

**Comment by ItaloCanturil** [comment]
Done ✅
